# main menu navigation
menu:
  home: /
  archives: /archives
  about: /about
  contact: /contact
  rss: /atom.xml

# Miscelaneous
favicon: https://pbs.twimg.com/media/DtWc0NgVAAMP3Cf.jpg

show_post_category: true
show_post_tags: true

active_nav: false # show active status on nav menu

sidebar: true # whether to show the sidebar
widgets:
  # - category
  # - tag
  # - archive
  - links
  - tagcloud
  - recent_posts
links:
  - title: "GitHub"
    url: http://www.github.com/mikenekoko
    intro: "GitHub"
  - title: "Twitter"
    url: https://twitter.com/mikene_koko
    intro: "twitter"
  - title: "Qiita"
    url: https://qiita.com/mikene_koko
    intro: "Qiita"

#site statistic
google_analytics:  